import Head from "next/head";
import Image from "next/image";
import { BsFillMoonStarsFill } from "react-icons/bs";
import "nes.css/css/nes.min.css";
import { useState } from "react";



export default function Home() {
  const [darkMode, setDarkMode] = useState(false)

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Amaan mirza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className=" py-4 mb-15 flex justify-between border-y-4" >

            <h1 className=" text-xl font-PressStart2P dark:text-white flex items-center px-4"><i class="nes-icon coin "></i>Resume</h1>

            <ul className=" flex items-center">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="text-2xl dark:text-white" /></li>
              <li><a href="#" className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 ">Portfolio</a></li>
            </ul>
          </nav>

        </section>
      </main>
    </div >
  );
}
