import Head from "next/head";
import { BsFillMoonStarsFill } from 'react-icons/bs'
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillInstagram
} from 'react-icons/ai'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import consulting from '../public/consulting.png'
import code from '../public/code.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Amaan mirza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between" >
            <h1 className=" text-xl font-burtons dark:text-white">Portfolio</h1>
            <ul className=" flex items-center">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=" cursor-pointer text-2xl dark:text-white" /></li>
              <li><a href="#" className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 ">Resume</a></li>
            </ul>
          </nav>
          <div className=" text-center p-10 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">Amaan mirza</h2>
            <h3 className=" text-2xl py-2 dark:text-white">Developer and designer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-white">
              I am a developer and designer based in India. I have a passion for web design and love to create for web and mobile devices.
            </p>
          </div>
          <div className=" text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
            <a href="https://www.instagram.com/amaanmirza_am/"><AiFillInstagram /></a>
            <a href="https://twitter.com/Amaan81272701"><AiFillTwitterCircle /></a>
            <a href="https://www.linkedin.com/in/amaan-mirza-50010422a/"><AiFillLinkedin /></a>
          </div>
          <div className=" relative mx-auto bg-gradient-to-b from-teal-500 to-white rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={deved} layout="fill" objectFit="cover" alt="Amaan mirza" />
          </div>
        </section>

        <section>
          <div>
            <h3 className=" text-3xl py-1 dark:text-white">Services I offer</h3>
            <p className=" text-md py-2 leading-8 text-gray-800 dark:text-whit dark:text-white">
              Since beginning my journey as a freelance designer nearly 10 years ago, I&apos;ve done remote work for <span className="text-teal-500">agencies</span> , consulted for <span className=" text-teal-500">startups</span>, and collaborated with talented people to create digital products for both business and consumer use. I&apos;m quietly confident, naturally curious, and perpetually working on improving my chops one design problem at a time.
            </p>
          </div>
          <div>
            <div className=" text-center mx-auto shadow-lg p-10 rounded-xl my-10 dark:text-white">
              <Image className="mx-auto" src={design} alt="none" width={100} height={100} />
              <h3 className=" text-lg font-medium pt-8 pb-12 dark:text-white">
                Beautiful designs
              </h3>
              <p className=" py-2 dark:text-white">
                creating elegant designs suited for your business
              </p>
              <h4 className=" py-4  text-teal-600 dark:text-white"> Design tools I use</h4>
              <p classname="py-1 text-gray-800  dark:text-white">Photoshop</p>
              <p classname="py-1 text-gray-800  dark:text-white">Illustrator</p>
              <p classname="py-1 text-gray-800  dark:text-white">Figma</p>
            </div>
            <div className=" text-center mx-auto shadow-lg p-10 rounded-xl my-10 dark:text-white">
              <Image className="mx-auto" src={consulting} alt="none" width={100} height={100} />
              <h3 className=" text-lg font-medium pt-8 pb-12 dark:text-whit dark:text-white">
                Beautiful designs
              </h3>
              <p className=" py-2 dark:text-white">
                creating elegant designs suited for your business
              </p>
              <h4 className=" py-4  text-teal-600 dark:text-white"> Design tools I use</h4>
              <p classname="py-1 text-gray-800 ">Photoshop</p>
              <p classname="py-1 text-gray-800 ">Illustrator</p>
              <p classname="py-1 text-gray-800 ">Figma</p>
            </div>
            <div className=" text-center mx-auto shadow-lg p-10 rounded-xl my-10 dark:text-white">
              <Image className="mx-auto" src={code} alt="none" width={100} height={100} />
              <h3 className=" text-lg font-medium pt-8 pb-12">
                Beautiful designs
              </h3>
              <p className=" py-2">
                creating elegant designs suited for your business
              </p>
              <h4 className=" py-4  text-teal-600 dark:text-white"> Design tools I use</h4>
              <p classname="py-1 text-gray-800 dark:text-white">Photoshop</p>
              <p classname="py-1 text-gray-800 dark:text-white">Illustrator</p>
              <p classname="py-1 text-gray-800 dark:text-white">Figma</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className=" text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className=" text-md py-2 leading-8 text-gray-800 dark:text-white">
              Since beginning my journey as a freelance designer nearly 10 years ago, I&apos;ve done remote work for <span className="text-teal-500">agencies</span> , consulted for <span className=" text-teal-500">startups</span>, and collaborated with talented people to create digital products for both business and consumer use. I&apos;m quietly confident, naturally curious, and perpetually working on improving my chops one design problem at a time.
            </p>
          </div>
          <div className=" flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className=" basis-1/3 flex-1">
              <Image src={web1} alt="none" className="rounded-lg object-cover " width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image src={web2} alt="none" className="rounded-lg object-cover " width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image src={web3} alt="none" className="rounded-lg object-cover " width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image src={web4} alt="none" className="rounded-lg object-cover " width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image src={web5} alt="none" className="rounded-lg object-cover " width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image src={web6} alt="none" className="rounded-lg object-cover " width={'100%'} height={'100%'} layout="responsive" />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
